### ISSUE TITLE
[NEW-FEATURE] Add implementation of render ignore

### ISSUE THREAD

**Issue by Specter-13** [ix-ax/ix#11]

**Comment by PTKu** [comment]
\cib

**Comment by PTKu** [comment]
Branch [11-_NEW-FEATURE_Add_implementation_of_render_ignore](https://github.com/ix-ax/ix/tree/11-_NEW-FEATURE_Add_implementation_of_render_ignore) created!

**Comment by PTKu** [comment]
@Specter-13 this should be working already since it uses the mechanism already implemented in attribute compilation.
I tested it in the integration sandbox 

![image](https://user-images.githubusercontent.com/61538034/214816061-8bb9cab1-d021-4f7a-b46b-9d0ba334e4be.png)

We will need to unit test it in blazor since this was just imported from legacies see #25
